apiVersion: v1
kind: Pod
metadata:
  name: iscsi-test-pod
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "set -eux; mount | grep /data || true; echo hello > /data/hello.txt; ls -la /data; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: iscsi-test

