apiVersion: v1
kind: Namespace
metadata:
  name: immich

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs-pv
  labels:
    app: immich
    pv-role: library
spec:
  capacity:
    storage: 5Ti            # logical; NFS doesn’t enforce
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 192.168.30.4
    path: /mnt/large_pool/photos
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-static
  volumeName: immich-library-nfs-pv
  resources:
    requests:
      storage: 5Ti

