apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1
  storage:
    storageClass: truenas-iscsi
    size: 20Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - "CREATE EXTENSION vchord CASCADE;"
        - "CREATE EXTENSION earthdistance CASCADE;"

