---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgDLaxIqdwSARIK6szPt6MSp3neg0DfsffM5xZqDGWvVFE5KeTtbCGt0bsBt0moUFLnBne7NWitO4U6ktzkOQ4egF/tiWKo6Gm9jVTbosboWgE03h4PCU/eHGbQTSbGttLk+ojqmf3mJ5gqYHf6XEeYrEroZuVvRgBWJ8PWzP9vRrNEThuA3vg+vzbh9ksxCaK6lGfD7pobopdffsQCgrBnfYFYiW9MF/q4R3eyPE8Pd5oGN/YB1x8lhvSGKRLf7au3Yt2lGP1BCTXQkj/OaBhsP0VpvsxBYBNY0jo3kBz17u9cxCNoZHiSndSpv6ui06XcHq3EzQzHXpEVm1yjElDFOe5AHU7wB4ITOuvZ99u4VcbE9hpXQt37dYT2m2hQUqBD+0htde3No2paD4HXtXBz3FtdUUrAJC04QKDrihmWAMFt4j4yMO+IWgVHwQPSu1gHZEffTY/S2gO6WQ8uCX5kB1dpxp/1PnH5ENKnLeBSZlchQAqRJYqtBqR12ViJNmeMSeSjkQsUxCR/4zYqY/8WZd5q8SxobXvu6u9Xnms6q4J+KBbGrj4sz7n6/Qqx4Lt6NzS560p5+mtBA2+uuA4GX4/0G5MuFScEUnQhmh80s0Bn3D+zwXxp9hbqwGbv5GpmicTpxHMFzLPhDD5OGjpEoITUyWYy3TK9C2WWf2fxY6Wey0SdmSWuEljMnAyhB0FeiEEjYvXP1okYbzGtbiefqitfbCymXzIe6ga4tQORiVGxjaz+8PGbif7vV1eUF6nzOppF5+AkascQ=
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin
      namespace: vaultwarden
