apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-pv
  labels:
    pv-role: arr-downloads
spec:
  capacity:
    storage: 2Ti          
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static             
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noatime
  nfs:
    server: 192.168.30.4 
    path: /mnt/large_pool/downloads

