apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: ghostfolio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
