apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-data
  namespace: satisfactory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-retain
  resources:
    requests:
      storage: 20Gi
