---
apiVersion: v1
kind: Namespace
metadata:
  name: nova
---
apiVersion: v1
kind: Service
metadata:
  name: nova-external
  namespace: nova
spec:
  # No selector: we'll provide Endpoints manually
  ports:
    - name: http
      port: 80           # what Traefik will send to
      targetPort: 18789  # Nova port on the external service
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nova-external
  namespace: nova
subsets:
  - addresses:
      - ip: 192.168.40.203
    ports:
      - name: http
        port: 18789
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nova
  namespace: nova
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: http
    traefik.ingress.kubernetes.io/router.middlewares: default-internal-whitelist@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: traefik
  rules:
    - host: nova.mangelschots.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nova-external
                port:
                  number: 80
  tls:
    - hosts:
        - nova.mangelschots.org
      secretName: nova-mangelschots-org-tls
