---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: actual
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: actual
      app.kubernetes.io/instance: actual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actual
        app.kubernetes.io/instance: actual
    spec:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: actual
          image: actualbudget/actual-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          env:
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
          volumeMounts:
            - name: data
              mountPath: /data
          # Probes: TCP is safest if the app doesn't expose a health endpoint
          readinessProbe:
            tcpSocket:
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5006
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-data
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: actual-svc
  namespace: actual
  labels:
    app.kubernetes.io/name: actual
spec:
  selector:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: actual
  ports:
    - name: http
      protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual
  namespace: actual
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - actual.mangelschots.org
      secretName: actual-mangelschots-org-tls
  rules:
    - host: actual.mangelschots.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-svc
                port:
                  number: 5006

